"""Initial Baseline Schema v2"""
from alembic import op
import sqlalchemy as sa

revision = '001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.create_table('venues',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('display_name', sa.Text(), nullable=False, unique=True),
        sa.Column('source', sa.Text(), nullable=False, server_default='seatgeek'),
        sa.Column('source_venue_id', sa.Text(), nullable=True),
        sa.Column('city', sa.Text(), nullable=True),
        sa.Column('timezone', sa.Text(), nullable=False, server_default='America/Los_Angeles'),
        sa.Column('enabled', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('resolved_at', sa.Text(), nullable=True),
        sa.Column('created_at', sa.Text(), nullable=False),
        sa.UniqueConstraint('source', 'source_venue_id')
    )
    op.create_table('source_events',
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('source_event_id', sa.Text(), nullable=False),
        sa.Column('venue_id', sa.Integer(), sa.ForeignKey('venues.id', ondelete='SET NULL'), nullable=True),
        sa.Column('canonical_event_id', sa.Text(), nullable=True),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('venue_name', sa.Text(), nullable=False),
        sa.Column('performers_json', sa.Text(), nullable=True),
        sa.Column('starts_at_utc', sa.Text(), nullable=False),
        sa.Column('event_url', sa.Text(), nullable=False),
        sa.Column('status', sa.Text(), nullable=False, server_default='active'),
        sa.Column('first_seen_at', sa.Text(), nullable=False),
        sa.Column('last_seen_at', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('source', 'source_event_id')
    )
    op.create_table('rules',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('enabled', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('scope_type', sa.Text(), nullable=False, server_default='venue'),
        sa.Column('scope_venue_id', sa.Integer(), sa.ForeignKey('venues.id', ondelete='CASCADE'), nullable=True),
        sa.Column('scope_performer_slug', sa.Text(), nullable=True),
        sa.Column('scope_source', sa.Text(), nullable=True),
        sa.Column('scope_source_event_id', sa.Text(), nullable=True),
        sa.Column('max_unit_price_all_in', sa.Float(), nullable=False),
        sa.Column('max_order_total', sa.Float(), nullable=True),
        sa.Column('quantity_mode', sa.Text(), nullable=False, server_default='exact'),
        sa.Column('quantity_value', sa.Integer(), nullable=False, server_default='2'),
        sa.Column('minimum_identity_confidence', sa.Text(), nullable=False, server_default='high'),
        sa.Column('minimum_fee_confidence', sa.Text(), nullable=False, server_default='medium'),
        sa.Column('estimate_safety_margin_pct', sa.Float(), nullable=False, server_default='0.08'),
        sa.Column('realert_mode', sa.Text(), nullable=False, server_default='either'),
        sa.Column('realert_drop_dollars', sa.Float(), nullable=False, server_default='25.0'),
        sa.Column('realert_drop_percent', sa.Float(), nullable=False, server_default='0.10'),
        sa.Column('realert_cooldown_minutes', sa.Integer(), nullable=False, server_default='30'),
        sa.Column('realert_memory_hours', sa.Integer(), nullable=False, server_default='24'),
        sa.Column('rule_fingerprint', sa.Text(), nullable=False),
        sa.Column('created_at', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.Text(), nullable=False)
    )
    op.create_table('rule_section_matchers',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('rule_id', sa.Integer(), sa.ForeignKey('rules.id', ondelete='CASCADE'), nullable=False),
        sa.Column('action', sa.Text(), nullable=False, server_default='include'),
        sa.Column('matcher_type', sa.Text(), nullable=False, server_default='exact'),
        sa.Column('matcher_value', sa.Text(), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0')
    )
    op.create_table('rule_event_bindings',
        sa.Column('rule_id', sa.Integer(), sa.ForeignKey('rules.id', ondelete='CASCADE'), nullable=False),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('source_event_id', sa.Text(), nullable=False),
        sa.Column('bound_at', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('rule_id', 'source', 'source_event_id')
    )
    op.create_table('section_aliases',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('venue_id', sa.Integer(), sa.ForeignKey('venues.id', ondelete='CASCADE'), nullable=False),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('raw_section', sa.Text(), nullable=False),
        sa.Column('normalized_section', sa.Text(), nullable=True),
        sa.Column('status', sa.Text(), nullable=False, server_default='pending'),
        sa.Column('first_seen_at', sa.Text(), nullable=False),
        sa.Column('approved_at', sa.Text(), nullable=True),
        sa.UniqueConstraint('venue_id', 'source', 'raw_section')
    )
    op.create_table('listings_current',
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('source_listing_id', sa.Text(), nullable=False),
        sa.Column('identity_type', sa.Text(), nullable=False, server_default='source_id'),
        sa.Column('identity_confidence', sa.Text(), nullable=False, server_default='high'),
        sa.Column('source_event_id', sa.Text(), nullable=False),
        sa.Column('raw_section', sa.Text(), nullable=True),
        sa.Column('normalized_section', sa.Text(), nullable=True),
        sa.Column('raw_row', sa.Text(), nullable=True),
        sa.Column('raw_seats', sa.Text(), nullable=True),
        sa.Column('quantity_available', sa.Integer(), nullable=False),
        sa.Column('available_quantities_json', sa.Text(), nullable=True),
        sa.Column('unit_price_listed', sa.Float(), nullable=True),
        sa.Column('unit_fee_amount', sa.Float(), nullable=True),
        sa.Column('unit_price_all_in', sa.Float(), nullable=True),
        sa.Column('price_basis', sa.Text(), nullable=False, server_default='unknown'),
        sa.Column('fee_confidence', sa.Text(), nullable=True),
        sa.Column('currency', sa.Text(), nullable=False, server_default='USD'),
        sa.Column('listing_url', sa.Text(), nullable=False),
        sa.Column('payload_hash', sa.Text(), nullable=False),
        sa.Column('hash_algo_version', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('consecutive_missing_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('first_seen_at', sa.Text(), nullable=False),
        sa.Column('last_seen_at', sa.Text(), nullable=False),
        sa.Column('inactive_at', sa.Text(), nullable=True),
        sa.Column('status', sa.Text(), nullable=False, server_default='active'),
        sa.Column('adapter_version', sa.Text(), nullable=False),
        sa.Column('parser_version', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('source', 'source_listing_id')
    )
    op.create_table('listing_price_history',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('source_listing_id', sa.Text(), nullable=False),
        sa.Column('observed_at', sa.Text(), nullable=False),
        sa.Column('unit_price_listed', sa.Float(), nullable=True),
        sa.Column('unit_price_all_in', sa.Float(), nullable=True),
        sa.Column('price_basis', sa.Text(), nullable=False),
        sa.Column('quantity_available', sa.Integer(), nullable=True)
    )
    op.create_table('event_price_snapshots',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('source_event_id', sa.Text(), nullable=False),
        sa.Column('observed_at', sa.Text(), nullable=False),
        sa.Column('lowest_price', sa.Float(), nullable=True),
        sa.Column('average_price', sa.Float(), nullable=True),
        sa.Column('highest_price', sa.Float(), nullable=True),
        sa.Column('listing_count', sa.Integer(), nullable=True),
        sa.Column('visible_listing_count', sa.Integer(), nullable=True),
        sa.Column('gate_decision', sa.Text(), nullable=False),
        sa.Column('gate_reason', sa.Text(), nullable=True)
    )
    op.create_table('fee_models',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('venue_id', sa.Integer(), sa.ForeignKey('venues.id', ondelete='CASCADE'), nullable=True),
        sa.Column('fee_rate_pct', sa.Float(), nullable=False, server_default='1.28'),
        sa.Column('fee_fixed', sa.Float(), nullable=False, server_default='3.50'),
        sa.Column('sample_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('residual_stddev', sa.Float(), nullable=True),
        sa.Column('confidence', sa.Text(), nullable=False, server_default='low'),
        sa.Column('last_calibrated_at', sa.Text(), nullable=True),
        sa.UniqueConstraint('source', 'venue_id')
    )
    op.create_table('fee_observations',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('venue_id', sa.Integer(), sa.ForeignKey('venues.id', ondelete='CASCADE'), nullable=True),
        sa.Column('source_event_id', sa.Text(), nullable=True),
        sa.Column('listed_price', sa.Float(), nullable=False),
        sa.Column('actual_all_in', sa.Float(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.Column('observed_at', sa.Text(), nullable=False),
        sa.Column('entered_via', sa.Text(), nullable=False, server_default='telegram')
    )
    op.create_table('alert_state',
        sa.Column('rule_id', sa.Integer(), sa.ForeignKey('rules.id', ondelete='CASCADE'), nullable=False),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('listing_identity', sa.Text(), nullable=False),
        sa.Column('currently_qualifying', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('reason_fingerprint', sa.Text(), nullable=True),
        sa.Column('rule_fingerprint', sa.Text(), nullable=True),
        sa.Column('last_qualifying_price', sa.Float(), nullable=True),
        sa.Column('last_alert_price', sa.Float(), nullable=True),
        sa.Column('last_alert_at', sa.Text(), nullable=True),
        sa.Column('transition_sequence', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('updated_at', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('rule_id', 'source', 'listing_identity')
    )
    op.create_table('alert_decisions',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('decided_at', sa.Text(), nullable=False),
        sa.Column('rule_id', sa.Integer(), nullable=False),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('listing_identity', sa.Text(), nullable=False),
        sa.Column('branch', sa.Integer(), nullable=False),
        sa.Column('outcome', sa.Text(), nullable=False),
        sa.Column('inputs_json', sa.Text(), nullable=False)
    )
    op.create_table('alert_outbox',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('payload_json', sa.Text(), nullable=False),
        sa.Column('dedupe_key', sa.Text(), nullable=False),
        sa.Column('status', sa.Text(), nullable=False, server_default='pending'),
        sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.Text(), nullable=False),
        sa.Column('next_attempt_at', sa.Text(), nullable=False),
        sa.Column('sent_at', sa.Text(), nullable=True)
    )
    op.create_table('poll_runs',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('tier', sa.Integer(), nullable=False),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('source_event_id', sa.Text(), nullable=False),
        sa.Column('started_at', sa.Text(), nullable=False),
        sa.Column('completed_at', sa.Text(), nullable=True),
        sa.Column('status', sa.Text(), nullable=False),
        sa.Column('pagination_complete', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('inventory_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('new_listing_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('changed_listing_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('transport_rung', sa.Integer(), nullable=True),
        sa.Column('argus_status', sa.Text(), nullable=True),
        sa.Column('extractor_used', sa.Text(), nullable=True),
        sa.Column('egress_used', sa.Text(), nullable=True),
        sa.Column('http_status', sa.Integer(), nullable=True),
        sa.Column('parser_version', sa.Text(), nullable=True),
        sa.Column('error_code', sa.Text(), nullable=True),
        sa.Column('error_summary', sa.Text(), nullable=True),
        sa.Column('capture_reference', sa.Text(), nullable=True)
    )
    op.create_table('transport_health',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('domain', sa.Text(), nullable=False),
        sa.Column('rung', sa.Integer(), nullable=False),
        sa.Column('attempts_50', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('successes_50', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('blocked_until', sa.Text(), nullable=True),
        sa.Column('consecutive_blocks', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('updated_at', sa.Text(), nullable=False),
        sa.UniqueConstraint('domain', 'rung')
    )

def downgrade() -> None:
    pass
